### ISSUE TITLE
datasets problems

### ISSUE THREAD

**Issue by 513617298** [scil-vital/TrackToLearn#10]
Can you give the hcp datasets?Because the hcp experiment in your previous code is difficult to reproduce。And I find out that hcp is lack of the gt_bundle_attributes.json

**Comment by AntoineTheb** [comment]
Hi @513617298 . In the coming months I will make new datasets and code available. I will keep you updated once this is done.

**Comment by gaunny** [comment]
Hi, I would also like to know the **scoring_data** for the **HCP data and tractoinferno data**, including files like gt_bundles_attributes.json. Currently I see that only ISMRM2015 and FiberCup contain them in public dataset. Also, I'd like to know how the **cluster_threshold** etc. in the gt_bundles_attributes.json file is obtained? I downloaded the original FiberCup and ISMRM2015 datasets and they do not contain them. Thank you.

**Comment by AntoineTheb** [comment]
Hi @gaunny ,

Unfortunately, there is no scoring data for the HCP and Tractoinferno datasets as these are in-vivo. For now, I would suggest training solely on ISMRM2015 and the FiberCup so that you can validate the progression of your agent's training.

As for the `cluster_threshold` parameter, I would suggest taking a look at RecoBundlesX, which is what powers the version of the Tractometer used in this work: https://scil-documentation.readthedocs.io/en/latest/our_tools/recobundles.html

The FiberCup and ISMRM2015 datasets already have the correct values set for recobundles. As mentionned previously, there is no config file for HCP and Tractoinferno as they do not contain ground-truth bundles. Tractoinferno does have a set of reference bundles, but it would require some work to make them compatible with the Tractometer.

Hope that helps !
