### ISSUE TITLE
problem with tracking reward

### ISSUE THREAD

**Issue by flsinz** [scil-vital/TrackToLearn#18]
Hi, for me, the target reward currently crashes in line: https://github.com/scil-vital/TrackToLearn/blob/a6bed01f574ceec6358bf18d49444de4261ace76/TrackToLearn/environments/reward.py#L235 . The reason is that dipy/stateful_tractogram expects a nifty/trk file/filename while this line https://github.com/scil-vital/TrackToLearn/blob/a6bed01f574ceec6358bf18d49444de4261ace76/TrackToLearn/environments/env.py#L144 assigns the input volume, i.e. a TrackToLearn.datasets.utils.MRIDataVolume object. Am I missing something, and if not, any hint how to fix it without changing it in too many places? Thanks in advance :)

**Comment by AntoineTheb** [comment]
Hi Fabian !

Oops, looks like I forgot to remove this part of the code when releasing the framework. If I'm looking at the correct line, this is where an SFT is constructed to be passed to the Tractometer for scoring. However, rewarding from the Tractometer is not something I have "officially" worked on and is not included in the latest paper.

But, since the cat's out the bag, I'll fix the code to make it work :) I'll make a few adjustments to pass a file reference, shouldn't take too long.

Thanks for trying out this new version of Track-to-Learn !

**Comment by flsinz** [comment]
Hi Antoine, nice, fast response :) Currently, my agents are struggling with crossing regions, so I thought the target reward might incentivise them to make the right decision in those sections. I'm happy to drop the tactometer dependency, any idea how to reward them better in crossings? Thanks a lot

**Comment by AntoineTheb** [comment]
Yeah, crossing regions are still an open problem with Track-to-Learn. So far I've found that agents tend to _mostly_ learn to cross them as it fits the reward function somewhat better (more alignment with itself and the underlying peaks), but this is not a guarantee. One thing that can help, but is somewhat of a hack, is to use a bigger step size. There's less chance of taking an unexpected turn if you spend less time in the crossing. 

Improvements-wise, using the Tractometer (I've "fixed" its usage in #20)  would definitely help. However, I would also recommend moving to the "Tractometer 2.0" (https://www.nature.com/articles/s41598-023-28560-w, https://tractometer.org/tractometer/bundle_segmentation/ using ROIs) as the "first" Tractometer uses RBx (https://scil-documentation.readthedocs.io/en/latest/our_tools/recobundles.html) which can sometimes do innacurate segmention, especially on the FiberCup.

Another improvement to the reward function would be to reward self-alignment with multiple past segments, not just the last. However this might prevent agent from reconstructing curves such as the U bundle at the top of the FiberCup, or the Fornix in the WM. I've thought about using the "first derivative" of the streamline (for a lack of a better word) as the self-alignment reward instead, so that straight lines and smooth curves would be rewarded equally, but I've yet to formalize this idea and try it.

Hope that helps, let me know what you come up with !

**Comment by AntoineTheb** [comment]
Merging the PR closed this issue, I'm reopening it for future discussions.

**Comment by flsinz** [comment]
Thanks a lot for the tips. I now have a couple of ideas to try; afterwards, I would be thrilled to circle back and discuss some more.

**Comment by AntoineTheb** [comment]
Sure thing ! Cheers !
