### ISSUE TITLE
Data and experiment parameters for reproduction of the results

### ISSUE THREAD

**Issue by flsinz** [scil-vital/TrackToLearn#8]
Hi @AntoineTheb, 

I'm currently working on RL-based tractography, and your work is a great starting point. I would like to reproduce the results from your initial publication to test if some of the possible extensions bring any real improvement. Due to the many moving parts, however, I found this tricky so far. I would be very grateful if you could provide some insight/ link to the exact experimental data and parameters.

The main problem I'm currently facing is that the fods for the fibercup dataset you provided in another issue thread don't look right to me. Here is what I obtain when just loading them into mrview: 
![fibercub_ttl](https://user-images.githubusercontent.com/31001953/194285869-47123a2b-a141-4d06-b7b6-5a3f0fd9adc8.png)

Maybe I miss some different convention for the spharm coeffs? Your agent learns better on this data, however than when I'm trying to provide a corrected version. 

Thank you in advance for any help.

Kind regards, Fabian

**Comment by AntoineTheb** [comment]
Hi and thank you for your interest in Track-to-Learn ! 

Some bug in the original implementation made reproducing the results presented in the MedIA paper impossible, and this is why I did not share the data. **However**, I have been working on the framework since then (amongst other things, why is why updates are slow, sorry) and I will be submitting for publication an updated version of the paper in the coming months, including data and weights. 

In a nearer future, I also have been adding features to the framework, such as WM/GM seeding, CMC from [1], support for asymmetric-fODFs and an updated version of the SAC algorithm. I have already updated the code and will update the readme (with links to data and weights) since I am presenting these improvements in this workshop: https://www.ismrm.org/workshops/2022/Diffusion/ The readme should be updated in the coming days.

To answer your question more directly, the fODFs provided are in the `descoteaux07` basis, not the `tournier07` basis. See [2] for more info. MRView only supports ODFs in the `tournier07` basis and displays `descoteaux07`-based ODFs incorrectly. I am not too familiar with MRtrix, but you can convert from one basis to another using scilpy (https://github.com/scilus/scilpy) with the `scil_convert_sh_basis.py` script.

Hope this helps, I will keep you updated on the framework !

[1]: Towards quantitative connectivity analysis: reducing tractography biases, https://www.sciencedirect.com/science/article/pii/S1053811914003541?via%3Dihub
[2]: DIPY - Spherical Harmonic bases, https://dipy.org/documentation/1.4.1./theory/sh_basis/

**Comment by flsinz** [comment]
Thanks a lot for the quick response. The change in basis explains my issues, I must have overlooked that. Looking forward to the additional features and the updated data. Thanks also for the tip with the basis conversion, much appreciated.

**Comment by AntoineTheb** [comment]
So I managed to squeeze in some time to update the readme today @FabianKTH . Let me know if you have questions. The bash scripts in `scripts` should provide a solid ground for running and modifying the framework.

**Comment by flsinz** [comment]
This is great, I managed to run the experiments with the provided data and configurations and train the agents. This enables me to evaluate our modifications against the original algorithm as a baseline. Thanks to @AntoineTheb for taking care of this. Also nice with the new features, particularly the dropping of the antipodal symmetry of the fodf.

**Comment by AntoineTheb** [comment]
That's great ! Let me know if you want to discuss ideas and projects or if you need further help running and modifying the framework. Enjoy !
